language: objective-c
osx_image: xcode8.3

notifications:
  email:
    - khoi.geeky@gmail.com
    - cuongnt04230@gmail.com

before_install:
    - gem update fastlane --no-ri --no-rdoc --no-document
    - pod repo update --silent

install:
    - cat ./Podfile

script: ./build.sh