language: objective-c
osx_image: xcode8.3

notifications:
  email:
    - khoi.geeky@gmail.com
    - cuongnt04230@gmail.com

before_install:
    - bundle install

install:
    - cat ./Podfile

script:
    - bundle exec fastlane ios beta